---
epos4_0:
 vendor_id: 0x000000fb
 product_id: 0x65520000
 slave_position: 0
 slave_alias: 0

 pdo_entry_info:
  indexes: 
   - 0x6040
   - 0x60FF
   - 0x60B1
   - 0x6060
   - 0x60FE
   - 0x6041
   - 0x6064
   - 0x606C
   - 0x6077
   - 0x6061
   - 0x60FD
  subindexes:
   - 0
   - 0
   - 0
   - 0
   - 1
   - 0
   - 0
   - 0
   - 0
   - 0
   - 0
  bit_lengths:
   - 16
   - 32
   - 32
   - 8
   - 32
   - 16
   - 32
   - 32
   - 16
   - 8
   - 32
  rxpdo_address: 0x1600
  rxpdo_size: 5
  txpdo_address: 0x1a00
  txpdo_size: 6
  

 slave_sync_info:
  
  num_sync_managers: 4
 
  sync_manager_directions:
   - 1
   - 2
   - 1
   - 2
 
  number_of_pdos:
   - 0
   - 0
   - 1
   - 1
 
  pdo_index_diff:
   - "NULL"
   - "NULL"
   - 0
   - 1
 
  watchdog_mode:
   - 2
   - 2
   - 1
   - 2