---
startup_config:

 -
  slave_name: "EL7221_9015_0"
  sdo_index: 0x2002
  sdo_subindex: 0x55
  data_type: uint8
  data_value: 0x05
 -
  slave_name: "EL7221_9015_1"
  sdo_index: 0x2002
  sdo_subindex: 0x55
  data_type: uint8
  data_value: 0x05

 -
  slave_name: "EL7221_9015_0"
  sdo_index: 0x2010
  sdo_subindex: 0x0D
  data_type: uint8
  data_value: 0x02

 -
  slave_name: "EL7221_9015_1"
  sdo_index: 0x2010
  sdo_subindex: 0x0D
  data_type: uint8
  data_value: 0x02 

...
---

controller_config:
 
 domain_names:
  - domain_1
 log_directory_path: "/home/naci/Projects/igh_master/logs/"
 cycle_period: 500

 debug_info:
  print_diagnostics_period: 1 # log period in seconds.
  keep_track_of:
    - 
     owner_name: EL7221_9015_0
     data_name: current_position
    - 
     owner_name: EL7221_9015_0 
     data_name: current_velocity
    - 
     owner_name: EL7221_9015_0
     data_name: info_data
    - 
     owner_name: EL7221_9015_1 
     data_name: current_position
    - 
     owner_name: EL7221_9015_1
     data_name: current_velocity
    - 
     owner_name: EL7221_9015_1  
     data_name: info_data
...
---
slave_name: "EK1100_0"
 
slave_type: "coupler"

domain_name: domain_1

num_of_slaves: 1

vendor_id: 0x00000002

product_id: 0x044c2c52

slave_position: 0

slave_alias: 0
...
---

slave_name: "EL7221_9015"

slave_type: "driver"

num_of_slaves: 2

domain_name: domain_1
#slave_base_names:
# -
# - 

vendor_id: 0x00000002

product_id: 0x1c353052

slave_position: 1

slave_alias: 0

pdo_names:
 - "ctrl_word"
 - "target_velocity"
 - "op_mode"
 - "status_word"
 - "current_position"
 - "current_velocity"
 - "current_torque"
 - "info_data"
 - "op_mode_display"
# Must be in the same order with pdo_names
pdo_types: 
 - uint16
 - int32
 - uint8
 - 
 -
 -
 -
 -
 -

pdo_entry_info:
 indexes:
  - 0x6040
  - 0x60ff
  - 0x6060
  - 0x6041
  - 0x6064
  - 0x606c
  - 0x6070
  - 0x2008
  - 0x6061
 subindexes:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 0
  
 bit_lengths:
  - 16
  - 32
  - 8
  - 16
  - 32
  - 32
  - 16
  - 16
  - 8
  
 rxpdo_address: 0x1600
 rxpdo_size: 3
 txpdo_address: 0x1a00
 txpdo_size: 6
 rxpdo_indexes:
  - 0x1600
  - 0x1601
  - 0x1608
 txpdo_indexes:
  - 0x1a00
  - 0x1a01
  - 0x1a02
  - 0x1a03
  - 0x1a0b
  - 0x1a0e

slave_sync_info:

 num_sync_managers: 4

 sync_manager_directions:
  - 1
  - 2
  - 1
  - 2
 number_of_pdos:
  - 0
  - 0
  - 3
  - 6

 pdo_index_diff:
  - "NULL"
  - "NULL"
  - 0
  - 3

 watchdog_mode:
  - 2
  - 2
  - 2
  - 2

dc_info:
 assign_activate: 0x0700 
 sync0_cycle: 2000000 
 sync0_shift: 0 
 sync1_cycle: 2000000 
 sync1_shift: 0

generator_info:
  - "ctrl_word"
  - "target_velocity"
  - "op_mode"
  - "status_word"
  - "current_position"
  - "current_velocity"
  - "current_torque"
  - "info_data"
  - "op_mode_display"

...
