# ---
# startup_config:

# ...

---
controller_config:

 domain_names:
  - domain_1
 log_directory_path: "/home/naci/Projects/igh_master/logs/"
 cycle_period: 500 

...
---

slave_name: epos4
slave_type: "driver"
num_of_slaves: 1
domain_name: domain_1
vendor_id: 0x000000fb
product_id: 0x65520000
slave_alias: 0
slave_position: 0
pdo_names:
 - "ctrl_word"
 - "target_velocity"
 - "velocity_offset"
 - "operation_mode"
 - "digital_output"
 - "status_word"
 - "current_position"
 - "current_velocity"
 - "current_torque"
 - "mode_display"
 - "digital_input"


pdo_entry_info:
 indexes:
  - 0x6040
  - 0x60FF
  - 0x60B1
  - 0x6060
  - 0x60FE
  - 0x6041
  - 0x6064
  - 0x606C
  - 0x6077
  - 0x6061
  - 0x60FD
 subindexes:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
 bit_lengths:
  - 16
  - 32
  - 32
  - 8
  - 32
  - 16
  - 32
  - 32
  - 16
  - 8
  - 32
 rxpdo_size: 5
 txpdo_size: 6
 rxpdo_indexes:
  - 0x1600
  #- 0x1601
  #- 0x1602
  #- 0x1603
  #- 0x1604
 txpdo_indexes:
  - 0x1a00
  #- 0x1a01
  #- 0x1a02
  #- 0x1a03
  #- 0x1a04
  #- 0x1a05

slave_sync_info:

 num_sync_managers: 4
 sync_manager_directions:
  - 1
  - 2
  - 1
  - 2
 number_of_pdos:
  - 0
  - 0
  - 1
  - 1
 pdo_index_diff:
  - "NULL"
  - "NULL"
  - 0
  - 1
 watchdog_mode:
  - 2
  - 2
  - 1
  - 2  
  

...